// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnwadclosbcsytucrmdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZud2FkY2xvc2Jjc3l0dWNybWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDA2NjQsImV4cCI6MjA2MDgxNjY2NH0.BfYz6_5_i3CzwnmzR4dyOaTwWTb0DpMzYhv_fyfD7tU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);